import type { ToolbarItemConfig } from './types'

/** 表格工具栏默认项（对齐 tiptap knowledge 场景子集） */
export const defaultSheetToolbarKeys: ToolbarItemConfig[] = [
  'insert',
  '|',
  'undo',
  'redo',
  'format-painter',
  'clearFormat',
  '|',
  'numberFormat',
  'decimalPlaces',
  '|',
  'fontSize',
  'bold',
  'italic',
  'strikethrough',
  'underline',
  '|',
  'textColor',
  'backgroundColor',
  '|',
  'align',
  '|',
  'filter',
  'conditionalFormat',
  'protect',
  'freeze',
  'link',
  'formula',
  '|',
  'findAndReplace',
]
